name: server
description: A server app using the shelf package.
version: 1.0.0
publish_to: 'none'
resolution: workspace

environment:
  sdk: ^3.11.0

dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.2
  dotenv: ^4.2.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.1.4
  shared_logic:
    path: ../../packages/shared_logic # This link is vital!

dev_dependencies:
  http: ^1.2.2
  lints: ^6.0.0
  test: ^1.25.6
